type t =
| And of t * t                 (* &= *)
| Singleton of t               (* $1 *)
| OrPositive of Choice.t * t   (* !+= *)
| Exists of Term.t * t         (* e= *)
| Forall of (Term.t -> t)      (* a= *)
| End                          (* $ *)
| Index of Index.t * t         (* idx= *)
| Initial of Index.t           (* $i *)
| Cut of Lkf_formula.t * t * t (* c= *)
